// Future updates normally require replacing only this file.
const VERGIL_PASSAGES=[
{cite:'Aeneid 4.68–73',label:'The wounded deer',status:'Preparatory seen passage',title:'Dido as the wounded deer',instruction:'Read for the image before translating every word.',lines:['Ūritur īnfēlīx Dīdō tōtāque vagātur','urbe furēns, quālis conjectā cerva sagittā,','quam procul incautam nemora inter Crēsia fīxit','pāstor agēns tēlīs līquitque volātile ferrum','nescius: illa fugā silvās saltūsque peragrat','Dictaeōs; haeret laterī lētālis harundō.'],questions:[
{type:'Recognize familiar Latin',prompt:'What ordinary object does volātile ferrum describe?',choices:['A sword','An arrow','A shield'],answer:1,hint:'Ferrum can name a weapon; volātile tells how it moves.',feedback:'An arrow. “Flying iron” replaces ordinary sagitta with material and motion.'},
{type:'Recover ordinary vocabulary',prompt:'Which familiar word lies beneath lētālis harundō?',choices:['sagitta','silva','cerva'],answer:0,hint:'What reed-like object is lodged in the deer’s side?',feedback:'Sagitta. “Deadly reed” is an elevated expression for the arrow.'},
{type:'Read the image',prompt:'What corresponds to the arrow remaining in the deer?',choices:['Dido’s wound of love','Aeneas’ fleet','Carthage’s walls'],answer:0,hint:'The physical wound makes an emotional injury visible.',feedback:'Dido’s wound of love: she wanders while the wound remains fixed inside her.'}]},
{cite:'Aeneid 4.74–89',label:'Dido consumed by love',status:'Seen passage',title:'Love displaces Dido’s public life',instruction:'Lines 74–76 are context; the questions concentrate on lines 77–89.',context:[0,1,2],lines:['Nunc media Aenēān sēcum per moenia dūcit','Sīdoniāsque ostentat opēs urbemque parātam,','incipit effārī mediāque in vōce resistit;','Nunc eadem lābente diē convīvia quaerit,','Īliacōsque iterum dēmēns audīre labōrēs','exposcit pendetque iterum nārrantis ab ōre.','Post ubi dīgressī, lūmenque obscūra vicissim','lūna premit suādentque cadentia sīdera somnōs,','sōla domō maeret vacuā strātīsque relictīs','incubat. Illum absēns absentem auditque videtque,','aut gremiō Ascanium genitōris imāgine capta','dētinet, īnfandum sī fallere possit amōrem.','Nōn coeptae adsurgunt turrēs, nōn arma juventūs','exercet portūsve aut prōpugnācula bellō','tūta parant: pendent opera interrupta minaeque','mūrōrum ingentēs aequātaque māchina caelō.'],questions:[
{type:'Recover an ordinary expression',prompt:'What does pendet … nārrantis ab ōre mean?',choices:['She listens with complete attention','She interrupts repeatedly','She watches him leave'],answer:0,hint:'Someone who “hangs from another’s mouth” waits on every word.',feedback:'She hangs on every word. Vergil makes intense listening physical.'},
{type:'Recognize compression',prompt:'In genitōris imāgine capta, what has captivated Dido?',choices:['Ascanius’ resemblance to his father','A portrait','Her own father’s memory'],answer:0,hint:'Genitōris imāgine explains why holding Ascanius gives access to Aeneas.',feedback:'Ascanius’ resemblance to Aeneas. Capta compresses the causal idea.'},
{type:'Reconstruct word groups',prompt:'Which separated words belong together?',choices:['opera interrupta','arma tūta','mūrōrum aequāta'],answer:0,hint:'Match case, number, and gender.',feedback:'Opera interrupta, neuter plural nominative: “the unfinished works.”'},
{type:'Read for meaning',prompt:'What larger change do lines 86–89 show?',choices:['Dido’s obsession halts civic work','The Trojans finish the defenses','A storm destroys the towers'],answer:0,hint:'Notice repeated nōn and the interrupted works.',feedback:'Dido’s private obsession becomes a public crisis: Carthage’s work stops.'}]},
{cite:'Aeneid 4.331–336',label:'Aeneas answers Dido',status:'Seen AP passage',title:'Aeneas controls his response',instruction:'Find grammatical anchors, then recover the ordinary idea.',lines:['Dīxerat. Ille Jovis monitīs immōta tenēbat','lūmina et obnīxus cūram sub corde premēbat.','Tandem pauca refert: “Ego tē, quae plūrima fandō','ēnumerāre valēs, numquam, rēgīna, negābō','prōmeritam, nec mē meminisse pigēbit Elissae','dum memor ipse meī, dum spīritus hōs regit artūs.”'],questions:[
{type:'Recognize familiar Latin',prompt:'What ordinary Latin lies beneath lūmina here?',choices:['flammae','oculī','sīdera'],answer:1,hint:'Aeneas keeps part of his face motionless.',feedback:'Oculī. Lūmina (“lights”) is an elevated poetic expression for “eyes.”'},
{type:'Name the transformation',prompt:'Which transformation is Vergil using with lūmina?',choices:['Elevated synonym or metaphor','Omission of a verb','Poetic contraction'],answer:0,hint:'The word is fully spelled and tenēbat is present.',feedback:'Elevated synonym or metaphorical expression.'},
{type:'Recover the ordinary thought',prompt:'What does cūram sub corde premēbat mean?',choices:['He suppressed his concern','He placed a burden under his chest','He remembered Dido'],answer:0,hint:'Premere can mean “press down.”',feedback:'He suppressed his concern. Emotional control becomes a physical image.'}]}
];
