// Short practice units. Each combines 1–3 close-reading questions from the
// passage bank with two questions written specifically for the 3–4-line chunk.
const strategyQuestion=(label,why)=>({type:'Use the transformation table',prompt:'Which transformation or reading move is most useful in this section?',choices:[label,'Separated word groups','Omission (ellipsis)'],answer:0,hint:'Look for the feature that makes familiar Latin appear unfamiliar.',feedback:why});
const meaningQuestion=(meaning,wrong1,wrong2)=>({type:'Recover the ordinary meaning',prompt:'Which plain-language paraphrase best captures this section?',choices:[meaning,wrong1,wrong2],answer:0,hint:'Anchor the finite verbs and rebuild the ordinary sequence of ideas.',feedback:meaning});
const routineQuestion={type:'Apply the method',prompt:'After spotting the poetic feature, what should you do next?',choices:['Replace it with ordinary language and rebuild the sentence','Translate each word in its printed order','Skip the difficult line entirely'],answer:0,hint:'The goal is to reveal the familiar Latin beneath the poetic surface.',feedback:'Replace the poetic expression with ordinary language, then reconstruct the sentence before polishing the translation.'};
const C=(cite,lines,core,strategy,why,meaning,wrong1,wrong2)=>({cite,lines,questions:[...core,strategyQuestion(strategy,why),meaningQuestion(meaning,wrong1,wrong2),...(core.length?[]:[routineQuestion])]});
const CHUNK_DATA={
'Aeneid 4.68–73':[
C('4.68–70',[0,1,2],[2],'Metaphor or image','The wounded-deer simile makes Dido’s invisible emotional injury visible.','Dido burns with love and wanders through the city like a deer struck by an unsuspected arrow.','Dido hunts a deer outside Carthage.','Aeneas wounds Dido during a hunt.'),
C('4.71–73',[3,4,5],[0,1],'Elevated synonym','Volātile ferrum and lētālis harundō replace the ordinary sagitta with “flying iron” and “deadly reed.”','The hunter leaves without knowing that the deadly arrow remains fixed in the fleeing deer’s side.','The hunter removes the arrow before the deer runs.','The deer attacks the shepherd with a reed.')],
'Aeneid 4.74–89':[
C('4.74–76',[0,1,2],[],'Compression','Mediā in vōce resistit compresses the idea that Dido begins speaking but stops in mid-sentence.','Dido shows Aeneas Carthage, begins to speak, and then stops midway.','Aeneas interrupts Dido’s tour of the city.','Dido completes a formal speech about Sidon.'),
C('4.77–79',[3,4,5],[0],'Metaphor or image','Pendet ab ōre makes absorbed listening physical: Dido “hangs from” the speaker’s mouth.','At evening Dido again demands the Trojan story and hangs on Aeneas’s every word.','Dido refuses to hear the Trojan story again.','Aeneas silently watches Dido speak.'),
C('4.80–83',[6,7,8,9],[],'Separated word groups','Obscūra belongs with lūna, and sōla with Dido understood; rebuilding those groups clarifies the scene.','After the guests leave and night encourages sleep, Dido lies alone in the empty house on abandoned couches.','The guests sleep together beneath a bright moon.','Dido orders the household to rebuild the couches.'),
C('4.83–85',[9,10,11],[1,2],'Compression','Genitōris imāgine capta compresses the cause: Ascanius captivates Dido because he resembles his father.','In Aeneas’s absence, Dido sees and hears him imaginatively and holds Ascanius because he resembles Aeneas.','Dido mistakes Ascanius for his grandfather.','Ascanius persuades Dido to forget Aeneas.'),
C('4.86–89',[12,13,14,15],[3],'Omission (ellipsis)','Repeated nōn and compact clauses require the reader to supply the civic work that no longer happens.','Carthage’s towers, military training, harbor defenses, and walls all remain unfinished.','The Trojans rapidly complete Carthage’s defenses.','A storm levels the newly completed walls.')],
'Aeneid 4.219–237':[
C('4.219–221',[0,1,2],[0,1,3],'Poetic name or epithet','Omnipotēns replaces Jupiter’s name, while amantīs uses a poetic accusative-plural ending.','Jupiter hears Iarbas praying at the altars and looks toward Carthage and the lovers who have forgotten a better reputation.','Mercury prays while Aeneas watches the city.','Dido asks Jupiter to protect the lovers.'),
C('4.222–225',[3,4,5,6],[2,4],'Poetic name or epithet','Dardanium ducem identifies Aeneas through Trojan ancestry; Vāde age also demonstrates elision in recitation.','Jupiter tells Mercury to summon the winds, fly to Carthage, and address the Trojan leader.','Aeneas commands Jupiter to send the west winds.','Mercury is ordered to remain with Dido.'),
C('4.226–229',[7,8,9,10],[3],'Poetic or alternate forms','Celerīs is the poetic -īs accusative plural that students know in prose as celerēs.','Mercury must carry Jupiter’s words swiftly because Aeneas is not attending to the cities promised by fate.','Mercury must build the promised cities himself.','Venus orders Aeneas to stay in Carthage.'),
C('4.230–233',[11,12,13,14],[],'Participial phrasing','Gravidam imperiīs bellōque frementem packs Italy’s future power and warfare into two modifiers.','Aeneas was promised as the man who would rule powerful Italy, continue Teucer’s line, and bring the world under laws.','Aeneas was promised a peaceful private life in Carthage.','Teucer was ordered to surrender Italy to Greece.'),
C('4.234–237',[15,16,17,18],[6,7],'Compression','Rapid questions and the compact jussive Nāviget turn Aeneas’s delay into failure of ambition and fatherhood.','Jupiter asks whether Aeneas begrudges Ascanius Rome and commands Aeneas to sail.','Jupiter asks Ascanius to abandon Rome.','Mercury is told to found a city in Africa.')],
'Aeneid 4.300–330':[
C('4.300–303',[0,1,2,3],[0,1],'Metaphor or image','The Bacchant simile supplies a mythic image for Dido’s uncontrolled movement and emotion.','Dido rages through the city like a Bacchant driven by nocturnal rites.','Dido calmly prepares a festival for Bacchus.','Aeneas performs a ritual on Mount Cithaeron.'),
C('4.304–307',[4,5,6,7],[2,3],'Poetic or alternate forms','Spērāstī contracts familiar spērāvistī; data dextera compresses a pledge into the image of a given hand.','Dido accuses Aeneas of hoping to conceal his betrayal and leave her land silently despite their pledge.','Dido praises Aeneas for openly announcing his departure.','Aeneas asks Dido to give him her right hand.'),
C('4.308–311',[8,9,10,11],[],'Elevated synonym','Hībernō sīdere and mediīs Aquilōnibus elevate the ordinary idea of sailing amid winter storms.','Dido is shocked that Aeneas prepares his fleet and hurries to sea in the middle of winter winds.','Dido urges Aeneas to wait for the summer breeze.','Aeneas has already returned safely from sea.'),
C('4.312–315',[12,13,14,15],[4],'Compression','Mēne fugis? compresses an emotional accusation by fronting mē and attaching the question marker -ne.','Dido asks whether Aeneas would cross a stormy sea even for Troy and then asks, “Is it me you are fleeing?”','Dido asks Aeneas to take her to Troy.','Aeneas asks whether Dido is fleeing Carthage.'),
C('4.316–319',[16,17,18,19],[5],'Metaphor or image','Exue mentem treats Aeneas’s intention like clothing that he could take off.','Dido appeals by their relationship and asks Aeneas to pity her collapsing house and change his intention.','Dido orders Aeneas to remove his armor.','Dido announces that her household is secure.'),
C('4.320–323',[20,21,22,23],[6],'Metaphor or image','Sīdera adībam turns Dido’s former reputation into a rise toward the stars.','Dido says that because of Aeneas she has gained enemies and lost the reputation that once raised her to the stars.','Dido says the Libyans have restored her honor.','Dido asks Aeneas to navigate by the stars.'),
C('4.324–327',[24,25,26,27],[7],'Loaded ordinary vocabulary','Hospes is deliberately inadequate: the hoped-for husband has become merely a guest.','Dido says only the name “guest” remains and fears either Pygmalion or Iarbas will destroy or capture her.','Dido welcomes Iarbas as her husband.','Pygmalion arrives to protect Carthage.'),
C('4.328–330',[28,29,30],[8],'Compression','Ōre referret compresses the idea that a child would reproduce Aeneas’s likeness in his face.','Dido imagines that a child resembling Aeneas would keep her from feeling entirely captured and abandoned.','Dido says Ascanius already resembles her.','Dido hopes a child will report Aeneas to the Trojans.')],
'Aeneid 4.331–336':[
C('4.331–333',[0,1,2],[0,1,2],'Elevated synonym','Lūmina is an elevated “lights” for eyes, while cūram premere turns emotional restraint into a physical act.','Aeneas keeps his eyes unmoved, presses down his concern, and finally begins a brief answer.','Aeneas closes his eyes and refuses to answer.','Jupiter forces Aeneas to forget Dido.'),
C('4.334–336',[3,4,5],[],'Poetic name or epithet','Elissa is an alternate poetic name for Dido; the repeated dum clauses set the duration of remembrance.','Aeneas says he will acknowledge Dido’s deserts and remember Elissa as long as he remains alive and aware.','Aeneas denies that Dido has done anything for him.','Aeneas promises to remain in Carthage forever.')],
'Aeneid 4.337–361':[
C('4.337–340',[0,1,2,3],[0,1,2],'Elision and compression','Nequ(e) ego elides final -e in recitation; conjugis taedās uses wedding torches for the whole marriage claim.','Aeneas says he did not hide his flight by stealth and never offered marriage; he then begins a condition about fate.','Aeneas admits secretly marrying Dido.','Aeneas says fate allowed him to choose any life.'),
C('4.341–344',[4,5,6,7],[3,4],'Poetic or alternate forms','Relliquiās is a metrical spelling of reliquiās, while Pergama is an elevated place-name for Troy.','If free to choose, Aeneas would tend Troy’s remnants and rebuild fallen Troy for the defeated.','Aeneas would abandon Troy even if free to choose.','Aeneas plans to rebuild Carthage for Priam.'),
C('4.345–348',[8,9,10,11],[5],'Poetic name or epithet','Grynean Apollo and Lycian lots are elevated cult and geographic labels for Apollo and his oracle.','Apollo’s oracles now command Aeneas to seek Italy, which he calls his love and homeland.','Mercury commands Aeneas to remain in Libya.','Dido’s oracle identifies Carthage as Aeneas’s homeland.'),
C('4.349–352',[12,13,14,15],[6,7],'Poetic name or epithet','Ausonia, Teucrī, and Hesperia are epic names for Italy, the Trojans, and the western land.','Aeneas argues that the Trojans too are divinely permitted to settle in Italy and seek a foreign kingdom.','Aeneas says only Phoenicians may settle abroad.','Dido forbids the Trojans to enter Carthage.'),
C('4.353–356',[16,17,18,19],[8],'Participial phrasing','Nested relative and participial ideas compress Ascanius’s injury: Aeneas is cheating his son of a destined Italian kingdom.','Anchises’ troubling image warns Aeneas in dreams, and Aeneas says his delay wrongs Ascanius.','Ascanius appears in Dido’s dreams and frightens her.','Anchises orders Aeneas to give Italy to Dido.'),
C('4.357–360',[20,21,22,23],[8,9],'Poetic name or epithet','Interpres dīvum identifies Mercury by his role; vōcem auribus hausī makes hearing into drinking in a voice.','Aeneas swears that Mercury brought Jupiter’s orders and that he saw and heard the god himself.','Aeneas says Apollo spoke through Dido.','Aeneas admits that he invented the divine message.'),
C('4.358–361',[21,22,23,24],[9,10],'Metaphor or image','Vōcem auribus hausī is a sensory metaphor, and incendere applies the language of fire to emotional torment.','Aeneas says he heard the divine voice, asks Dido to stop inflaming them both with complaints, and says he seeks Italy unwillingly.','Aeneas says Dido’s complaints persuade him to stay.','Aeneas claims he eagerly chose Italy for personal pleasure.')]
};
VERGIL_PASSAGES.forEach(p=>{p.chunks=(CHUNK_DATA[p.cite]||[]).map(c=>({...c,questions:c.questions.map(x=>Number.isInteger(x)?p.questions[x]:x)}));});
