// Short sense units. Boundaries follow complete ideas, so their length may vary.
const TRANSFORMATIONS=['Elevated synonym','Poetic name or epithet','Metaphor or image','Compression','Participial phrasing','Omission (ellipsis)','Separated word groups','Poetic or alternate forms'];
const strategyQuestion=(label,why)=>{
  const normalized=label==='Elision and compression'?'Compression':label==='Loaded ordinary vocabulary'?'Elevated synonym':label;
  const distractors=TRANSFORMATIONS.filter(x=>x!==normalized).slice(0,3);
  return {stage:3,type:'Name the transformation',prompt:'Now name the principal transformation you just used.',choices:[normalized,...distractors],answer:0,hint:'Match the reading move you used to the numbered reference table.',feedback:why};
};
const meaningQuestion=(meaning,wrong1,wrong2)=>({stage:2,type:'Rebuild the idea',prompt:'After replacing the poetic language with ordinary language, which paraphrase fits?',choices:[meaning,wrong1,wrong2],answer:0,hint:'Anchor the finite verbs and rebuild the ordinary sequence of ideas.',feedback:meaning});
const routineQuestion={stage:1,type:'Notice the Latin',prompt:'What should you do first with this short sense unit?',choices:['Locate the finite verbs and reconnect words that belong together','Translate strictly from left to right','Skip every unfamiliar-looking word'],answer:0,hint:'Begin with forms and syntax you already recognize.',feedback:'First locate the grammatical anchors and rebuild the word groups. Then replace poetic expressions with ordinary Latin.'};
const C=(cite,lines,core,strategy,why,meaning,wrong1,wrong2)=>({cite,lines,questions:[...core,...(core.length?[]:[routineQuestion]),meaningQuestion(meaning,wrong1,wrong2),strategyQuestion(strategy,why)]});
const CHUNK_DATA={
'Aeneid 4.68–73':[
C('4.68–71',[0,1,2,3],[],'Metaphor or image','The wounded-deer simile makes Dido’s invisible emotional injury visible.','Dido burns with love and wanders through the city like a deer struck by an unsuspected arrow.','Dido hunts a deer outside Carthage.','Aeneas wounds Dido during a hunt.'),
C('4.70–73',[2,3,4,5],[0,1],'Elevated synonym','Volātile ferrum and lētālis harundō replace the ordinary sagitta with “flying iron” and “deadly reed.”','The hunter leaves without knowing that the deadly arrow remains fixed in the fleeing deer’s side.','The hunter removes the arrow before the deer runs.','The deer attacks the shepherd with a reed.')],
'Aeneid 4.74–89':[
C('4.74–76',[0,1,2],[],'Compression','Mediā in vōce resistit compresses the idea that Dido begins speaking but stops in mid-sentence.','Dido shows Aeneas Carthage, begins to speak, and then stops midway.','Aeneas interrupts Dido’s tour of the city.','Dido completes a formal speech about Sidon.'),
C('4.77–79',[3,4,5],[0],'Metaphor or image','Pendet ab ōre makes absorbed listening physical: Dido “hangs from” the speaker’s mouth.','At evening Dido again demands the Trojan story and hangs on Aeneas’s every word.','Dido refuses to hear the Trojan story again.','Aeneas silently watches Dido speak.'),
C('4.80–84',[6,7,8,9,10],[],'Separated word groups','Obscūra belongs with lūna, and sōla with Dido understood; rebuilding those groups clarifies the scene.','After the guests leave and night encourages sleep, Dido lies alone in the empty house and imagines the absent Aeneas.','The guests sleep together beneath a bright moon.','Dido orders the household to rebuild the couches.'),
C('4.83–85',[9,10,11],[1],'Compression','Genitōris imāgine capta compresses the cause: Ascanius captivates Dido because he resembles his father.','In Aeneas’s absence, Dido imagines him and holds Ascanius because the boy resembles Aeneas.','Dido mistakes Ascanius for his grandfather.','Ascanius persuades Dido to forget Aeneas.'),
C('4.86–89',[12,13,14,15],[3],'Omission (ellipsis)','Repeated nōn and compact clauses require the reader to supply the civic work that no longer happens.','Carthage’s towers, military training, harbor defenses, and walls all remain unfinished.','The Trojans rapidly complete Carthage’s defenses.','A storm levels the newly completed walls.')],
'Aeneid 4.219–237':[
C('4.219–221',[0,1,2],[0,1],'Poetic name or epithet','Omnipotēns replaces Jupiter’s name, while amantīs uses a poetic accusative-plural ending.','Jupiter hears Iarbas praying at the altars and looks toward Carthage and the lovers who have forgotten a better reputation.','Mercury prays while Aeneas watches the city.','Dido asks Jupiter to protect the lovers.'),
C('4.222–223',[3,4],[4],'Compression','The compact commands Vāde age and lābere pennīs launch Mercury immediately; Vāde age also elides in recitation.','Jupiter turns to Mercury and commands him to go, summon the winds, and glide on his wings.','Aeneas commands Jupiter to send the west winds.','Mercury is ordered to remain with Dido.'),
C('4.224–229',[5,6,7,8,9,10],[2],'Poetic or alternate forms','Celerīs is the poetic -īs accusative plural that students know in prose as celerēs; Dardanium ducem is an epic title for Aeneas.','Mercury must address the Trojan leader in Carthage and swiftly carry Jupiter’s words because Aeneas ignores the cities promised by fate.','Mercury must build the promised cities himself.','Venus orders Aeneas to stay in Carthage.'),
C('4.229–233',[10,11,12,13,14],[],'Participial phrasing','Gravidam imperiīs bellōque frementem packs Italy’s future power and warfare into two modifiers.','Aeneas was promised as the man who would rule powerful Italy, continue Teucer’s line, and bring the world under laws.','Aeneas was promised a peaceful private life in Carthage.','Teucer was ordered to surrender Italy to Greece.'),
C('4.234–237',[15,16,17,18],[6,7],'Compression','Rapid questions and the compact jussive Nāviget turn Aeneas’s delay into failure of ambition and fatherhood.','Jupiter asks whether Aeneas begrudges Ascanius Rome and commands Aeneas to sail.','Jupiter asks Ascanius to abandon Rome.','Mercury is told to found a city in Africa.')],
'Aeneid 4.300–330':[
C('4.300–303',[0,1,2,3],[0,1],'Metaphor or image','The Bacchant simile supplies a mythic image for Dido’s uncontrolled movement and emotion.','Dido rages through the city like a Bacchant driven by nocturnal rites.','Dido calmly prepares a festival for Bacchus.','Aeneas performs a ritual on Mount Cithaeron.'),
C('4.304–309',[4,5,6,7,8,9],[2,3],'Poetic or alternate forms','Spērāstī contracts familiar spērāvistī; data dextera compresses a pledge into the image of a given hand.','Dido accuses Aeneas of hoping to conceal his departure despite their love, pledge, and her approaching death.','Dido praises Aeneas for openly announcing his departure.','Aeneas asks Dido to give him her right hand.'),
C('4.309–314',[9,10,11,12,13,14],[4],'Elevated synonym','Hībernō sīdere and mediīs Aquilōnibus elevate winter storm conditions; Mēne fugis? then compresses Dido’s accusation.','Dido marvels that Aeneas would sail in winter and asks whether even Troy would be sought across such seas—then asks whether he is fleeing her.','Dido urges Aeneas to wait for the summer breeze.','Aeneas asks whether Dido is fleeing Carthage.'),
C('4.314–319',[14,15,16,17,18,19],[5],'Metaphor or image','Exue mentem treats Aeneas’s intention like clothing that he could take off.','Through tears, their pledge, and their marriage, Dido asks Aeneas to pity her collapsing house and change his intention.','Dido orders Aeneas to remove his armor.','Dido announces that her household is secure.'),
C('4.320–324',[20,21,22,23,24],[6],'Metaphor or image','Sīdera adībam turns Dido’s former reputation into a rise toward the stars.','Dido says that because of Aeneas she has gained enemies, lost her former reputation, and is now being abandoned to die by a mere “guest.”','Dido says the Libyans have restored her honor.','Dido asks Aeneas to navigate by the stars.'),
C('4.323–327',[23,24,25,26,27],[7],'Elevated synonym','Hospes is deliberately inadequate: the hoped-for husband has become merely a guest.','Dido says only the name “guest” remains and fears either Pygmalion or Iarbas will destroy or capture her.','Dido welcomes Iarbas as her husband.','Pygmalion arrives to protect Carthage.'),
C('4.327–330',[27,28,29,30],[8],'Compression','Ōre referret compresses the idea that a child would reproduce Aeneas’s likeness in his face.','Dido imagines that a child resembling Aeneas would keep her from feeling entirely captured and abandoned.','Dido says Ascanius already resembles her.','Dido hopes a child will report Aeneas to the Trojans.')],
'Aeneid 4.331–336':[
C('4.331–332',[0,1],[0,1,2],'Elevated synonym','Lūmina is an elevated “lights” for eyes, while cūram premere turns emotional restraint into a physical act.','After Dido finishes, Aeneas keeps his eyes unmoved and presses down his concern beneath his heart.','Aeneas closes his eyes and refuses to answer.','Jupiter forces Aeneas to forget Dido.'),
C('4.333–336',[2,3,4,5],[],'Poetic name or epithet','Elissa is an alternate poetic name for Dido; the repeated dum clauses set the duration of remembrance.','Aeneas begins a brief answer: he will acknowledge Dido’s deserts and remember Elissa as long as he remains alive and aware.','Aeneas denies that Dido has done anything for him.','Aeneas promises to remain in Carthage forever.')],
'Aeneid 4.337–361':[
C('4.337–339',[0,1,2],[0,1,2],'Compression','Nequ(e) ego elides final -e in recitation; conjugis taedās uses wedding torches for the whole marriage claim.','Aeneas says he did not hide his flight by stealth and never offered the wedding torches or entered a marriage pact.','Aeneas admits secretly marrying Dido.','Aeneas says fate allowed him to choose any life.'),
C('4.340–344',[3,4,5,6,7],[3,4],'Poetic or alternate forms','Relliquiās is a metrical spelling of reliquiās, while Pergama is an elevated place-name for Troy.','If free to choose, Aeneas would tend Troy’s remnants and rebuild fallen Troy for the defeated.','Aeneas would abandon Troy even if free to choose.','Aeneas plans to rebuild Carthage for Priam.'),
C('4.345–346',[8,9],[5],'Poetic name or epithet','Grynean Apollo and Lycian lots are elevated cult and geographic labels for Apollo and his oracle.','Apollo and his Lycian oracle now command Aeneas to seek Italy.','Mercury commands Aeneas to remain in Libya.','Dido’s oracle identifies Carthage as Aeneas’s homeland.'),
C('4.347–350',[10,11,12,13],[7],'Poetic name or epithet','Phoenissam, Ausonia, and Teucrōs replace ordinary names with epic ethnic and geographic labels.','Aeneas calls Italy his love and homeland, then argues that the Trojans too may settle in Ausonia and seek a foreign kingdom.','Aeneas says only Phoenicians may settle abroad.','Dido forbids the Trojans to enter Carthage.'),
C('4.351–355',[14,15,16,17,18],[],'Poetic name or epithet','Hesperia is an epic name for Italy; nested clauses compress the claim that delay cheats Ascanius of his destined realm.','Anchises’ troubling image warns Aeneas in dreams, and Aeneas says his delay wrongs Ascanius by denying him Hesperia.','Ascanius appears in Dido’s dreams and frightens her.','Anchises orders Aeneas to give Italy to Dido.'),
C('4.356–359',[19,20,21,22],[8,9],'Poetic name or epithet','Interpres dīvum identifies Mercury by his role; vōcem auribus hausī makes hearing into drinking in a voice.','Aeneas swears that Mercury brought Jupiter’s orders and that he saw and heard the god himself.','Aeneas says Apollo spoke through Dido.','Aeneas admits that he invented the divine message.'),
C('4.360–361',[23,24],[10],'Metaphor or image','Incendere applies the language of fire to the emotional pain caused by Dido’s complaints.','Aeneas asks Dido to stop inflaming them both with complaints and says that he seeks Italy unwillingly.','Aeneas says Dido’s complaints persuade him to stay.','Aeneas claims he eagerly chose Italy for personal pleasure.')]
};
VERGIL_PASSAGES.forEach(p=>{p.chunks=(CHUNK_DATA[p.cite]||[]).map(c=>({...c,questions:c.questions.map(x=>Number.isInteger(x)?p.questions[x]:x)}));});
