// Future updates normally require replacing only this file.
const VERGIL_PASSAGES=[
{cite:'Aeneid 4.68–73',label:'The wounded deer',status:'Preparatory seen passage',title:'Dido as the wounded deer',instruction:'Read for the image before translating every word.',lines:['Ūritur īnfēlīx Dīdō tōtāque vagātur','urbe furēns, quālis conjectā cerva sagittā,','quam procul incautam nemora inter Crēsia fīxit','pāstor agēns tēlīs līquitque volātile ferrum','nescius: illa fugā silvās saltūsque peragrat','Dictaeōs; haeret laterī lētālis harundō.'],questions:[
{type:'Recognize familiar Latin',prompt:'What ordinary object does volātile ferrum describe?',choices:['A sword','An arrow','A shield'],answer:1,hint:'Ferrum can name a weapon; volātile tells how it moves.',feedback:'An arrow. “Flying iron” replaces ordinary sagitta with material and motion.'},
{type:'Recover ordinary vocabulary',prompt:'Which familiar word lies beneath lētālis harundō?',choices:['sagitta','silva','cerva'],answer:0,hint:'What reed-like object is lodged in the deer’s side?',feedback:'Sagitta. “Deadly reed” is an elevated expression for the arrow.'},
{type:'Read the image',prompt:'What corresponds to the arrow remaining in the deer?',choices:['Dido’s wound of love','Aeneas’ fleet','Carthage’s walls'],answer:0,hint:'The physical wound makes an emotional injury visible.',feedback:'Dido’s wound of love: she wanders while the wound remains fixed inside her.'}]},
{cite:'Aeneid 4.74–89',label:'Dido consumed by love',status:'Seen passage',title:'Love displaces Dido’s public life',instruction:'Lines 74–76 are context; the questions concentrate on lines 77–89.',context:[0,1,2],lines:['Nunc media Aenēān sēcum per moenia dūcit','Sīdoniāsque ostentat opēs urbemque parātam,','incipit effārī mediāque in vōce resistit;','Nunc eadem lābente diē convīvia quaerit,','Īliacōsque iterum dēmēns audīre labōrēs','exposcit pendetque iterum nārrantis ab ōre.','Post ubi dīgressī, lūmenque obscūra vicissim','lūna premit suādentque cadentia sīdera somnōs,','sōla domō maeret vacuā strātīsque relictīs','incubat. Illum absēns absentem auditque videtque,','aut gremiō Ascanium genitōris imāgine capta','dētinet, īnfandum sī fallere possit amōrem.','Nōn coeptae adsurgunt turrēs, nōn arma juventūs','exercet portūsve aut prōpugnācula bellō','tūta parant: pendent opera interrupta minaeque','mūrōrum ingentēs aequātaque māchina caelō.'],questions:[
{type:'Recover an ordinary expression',prompt:'What does pendet … nārrantis ab ōre mean?',choices:['She listens with complete attention','She interrupts repeatedly','She watches him leave'],answer:0,hint:'Someone who “hangs from another’s mouth” waits on every word.',feedback:'She hangs on every word. Vergil makes intense listening physical.'},
{type:'Recognize compression',prompt:'In genitōris imāgine capta, what has captivated Dido?',choices:['Ascanius’ resemblance to his father','A portrait','Her own father’s memory'],answer:0,hint:'Genitōris imāgine explains why holding Ascanius gives access to Aeneas.',feedback:'Ascanius’ resemblance to Aeneas. Capta compresses the causal idea.'},
{type:'Reconstruct word groups',prompt:'Which separated words belong together?',choices:['opera interrupta','arma tūta','mūrōrum aequāta'],answer:0,hint:'Match case, number, and gender.',feedback:'Opera interrupta, neuter plural nominative: “the unfinished works.”'},
{type:'Read for meaning',prompt:'What larger change do lines 86–89 show?',choices:['Dido’s obsession halts civic work','The Trojans finish the defenses','A storm destroys the towers'],answer:0,hint:'Notice repeated nōn and the interrupted works.',feedback:'Dido’s private obsession becomes a public crisis: Carthage’s work stops.'}]},
{cite:'Aeneid 4.331–336',label:'Aeneas answers Dido',status:'Seen AP passage',title:'Aeneas controls his response',instruction:'Find grammatical anchors, then recover the ordinary idea.',lines:['Dīxerat. Ille Jovis monitīs immōta tenēbat','lūmina et obnīxus cūram sub corde premēbat.','Tandem pauca refert: “Ego tē, quae plūrima fandō','ēnumerāre valēs, numquam, rēgīna, negābō','prōmeritam, nec mē meminisse pigēbit Elissae','dum memor ipse meī, dum spīritus hōs regit artūs.”'],questions:[
{type:'Recognize familiar Latin',prompt:'What ordinary Latin lies beneath lūmina here?',choices:['flammae','oculī','sīdera'],answer:1,hint:'Aeneas keeps part of his face motionless.',feedback:'Oculī. Lūmina (“lights”) is an elevated poetic expression for “eyes.”'},
{type:'Name the transformation',prompt:'Which transformation is Vergil using with lūmina?',choices:['Elevated synonym or metaphor','Omission of a verb','Poetic contraction'],answer:0,hint:'The word is fully spelled and tenēbat is present.',feedback:'Elevated synonym or metaphorical expression.'},
{type:'Recover the ordinary thought',prompt:'What does cūram sub corde premēbat mean?',choices:['He suppressed his concern','He placed a burden under his chest','He remembered Dido'],answer:0,hint:'Premere can mean “press down.”',feedback:'He suppressed his concern. Emotional control becomes a physical image.'}]},
{cite:'Aeneid 4.219–237',label:'Jupiter sends Mercury',status:'Seen AP passage',title:'Jupiter recalls Aeneas to his mission',instruction:'Use forms and context to unpack epithets, compressed commands, alternate endings, and elision.',lines:['Tālibus ōrantem dictīs ārāsque tenentem','audiit omnipotēns, oculōsque ad moenia torsit','rēgia et oblītōs fāmae meliōris amantīs.','Tum sīc Mercurium adloquitur ac tālia mandat:','“Vāde age, nāte, vocā Zephyrōs et lābere pennīs','Dardaniumque ducem, Tyriā Karthāgine quī nunc','exspectat fātīsque datās nōn respicit urbēs,','adloquere et celerīs dēfer mea dicta per aurās.','Nōn illum nōbīs genetrīx pulcherrima tālem','prōmīsit Grajumque ideō bis vindicat armīs;','sed fore quī gravidam imperiīs bellōque frementem','Ītaliam regeret, genus altō ā sanguine Teucrī','prōderet, ac tōtum sub lēgēs mitteret orbem.','Sī nūlla accendit tantārum glōria rērum','nec super ipse suā mōlītur laude labōrem,','Ascaniōne pater Rōmānās invidet arcēs?','Quid struit? Aut quā spē inimīcā in gente morātur','nec prōlem Ausoniam et Lāvīnia respicit arva?','Nāviget! Haec summa est, hic nostrī nūntius estō.”'],questions:[
{type:'Poetic epithet and omission',prompt:'Whom does omnipotēns identify in line 220?',choices:['Jupiter','Mercury','Aeneas'],answer:0,hint:'The all-powerful god hears the prayer and then commands Mercury.',feedback:'Jupiter. Vergil supplies the epithet “the all-powerful” and leaves the god’s name unstated.'},
{type:'Participial compression',prompt:'Whom do ōrantem and tenentem describe?',choices:['Iarbas, praying and holding the altars','Mercury, preparing to fly','Aeneas, looking at Carthage'],answer:0,hint:'Both participles are accusative singular and depend on audiit.',feedback:'Iarbas. Two participles compress the fuller idea that Jupiter heard him while he prayed and clung to the altars.'},
{type:'Poetic name',prompt:'Who is the Dardanius dux?',choices:['Aeneas','Ascanius','Iarbas'],answer:0,hint:'Dardanian points to Trojan ancestry; this leader is delaying in Carthage.',feedback:'Aeneas. Dardanius dux replaces his ordinary name with an elevated ethnic title.'},
{type:'Alternate poetic form',prompt:'What ordinary accusative-plural endings correspond to amantīs and celerīs?',choices:['amantēs and celerēs','amantōs and celerōs','amantium and celerium'],answer:0,hint:'Third-declension accusative plurals can appear poetically in -īs.',feedback:'Amantēs and celerēs. The poetic -īs ending can disguise forms students already know.'},
{type:'Elision',prompt:'Which version shows how Vāde age is normally heard in the hexameter?',choices:['Vād’ age','Vāde-age with both vowels fully separate','Vādage with a hard g joining both words'],answer:0,hint:'A final vowel is suppressed before a following word beginning with a vowel.',feedback:'Vād’ age. This is elision between words, unlike contraction inside a written word such as vincula → vincla.'},
{type:'Elision',prompt:'Where does another clear elision occur in the passage?',choices:['Lāvīni(a) arva','celerīs dēfer','fātīsque datās'],answer:0,hint:'Look for a final vowel followed immediately by an initial vowel.',feedback:'Lāvīni(a) arva. Final -a is elided before arva. The spelling remains unchanged on the page.'},
{type:'Recover the ordinary thought',prompt:'What does Ascaniōne pater Rōmānās invidet arcēs? ask?',choices:['Is Aeneas, as a father, denying Ascanius his Roman destiny?','Does Ascanius envy the towers already built at Rome?','Will Jupiter give Carthage to Ascanius?'],answer:0,hint:'Invidēre with the dative can mean “begrudge” or “deny”; Ascaniō is the person affected.',feedback:'Jupiter asks whether Aeneas is denying his son the Roman citadels promised by fate. The compact question turns delay into a failure of fatherhood.'},
{type:'Read for purpose',prompt:'What is Jupiter’s central command in the final line?',choices:['Aeneas must sail','Mercury must remain in Carthage','Ascanius must return to Troy'],answer:0,hint:'Nāviget is a present subjunctive used as a direct command.',feedback:'Aeneas must sail. Nāviget compresses the entire divine message into one forceful jussive: “Let him sail!”'}]},
{cite:'Aeneid 4.300–330',label:'Dido confronts Aeneas',status:'Seen AP passage',title:'Dido discovers the planned departure',instruction:'Recover the ordinary language beneath Bacchic imagery, compressed questions, and emotional metaphors.',lines:['Saevit inops animī tōtamque incēnsa per urbem','bacchātur, quālis commōtīs excita sacrīs','Thȳias, ubi audītō stimulant trietērica Bacchō','orgia nocturnusque vocat clāmōre Cithaerōn.','Tandem hīs Aenēān compellat vōcibus ultrō:','“Dissimulāre etiam spērāstī, perfide, tantum','posse nefās tacitusque meā dēcēdere terrā?','Nec tē noster amor nec tē data dextera quondam','nec moritūra tenet crūdēlī fūnere Dīdō?','Quīn etiam hībernō mōlīrī sīdere classem','et mediīs properās Aquilōnibus īre per altum,','crūdēlis? Quid, sī nōn arva aliēna domōsque','ignōtās peterēs, et Troja antīqua manēret,','Troja per undōsum peterētur classibus aequor?','Mēne fugis? Per ego hās lacrimās dextramque tuam tē','(quandō aliud mihi jam miserae nihil ipsa relīquī),','per cōnūbia nostra, per inceptōs hymenaeōs,','sī bene quid dē tē meruī, fuit aut tibi quicquam','dulce meum, miserēre domūs lābentis et istam,','ōrō, sī quis adhūc precibus locus, exue mentem.','Tē propter Libycae gentēs Nomadumque tyrannī','ōdēre, īnfēnsī Tyriī; tē propter eundem','exstīnctus pudor et, quā sōlā sīdera adībam,','fāma prior. Cui mē moribundam dēseris hospes','(hoc sōlum nōmen quoniam dē conjuge restat)?','Quid moror? An mea Pygmaliōn dum moenia frāter','dēstruat aut captam dūcat Gaetūlus Iarbās?','Saltem sī qua mihī dē tē suscepta fuisset','ante fugam subolēs, sī quis mihi parvulus aulā','lūderet Aenēās, quī tē tamen ōre referret,','nōn equidem omnīnō capta ac dēserta vidērer.”'],questions:[
{type:'Recover ordinary language',prompt:'What does inops animī communicate about Dido?',choices:['She has lost command of herself','She lacks political authority','She has forgotten Aeneas’s name'],answer:0,hint:'Inops means “lacking”; the genitive animī identifies what she lacks.',feedback:'She is without control of her mind or spirit. The compact phrase replaces a longer explanation of emotional collapse.'},
{type:'Poetic allusion',prompt:'Why does Vergil compare Dido to a Thȳias?',choices:['She rages like a Bacchant driven by ritual frenzy','She plans a calm religious sacrifice','She disguises herself as a Trojan priestess'],answer:0,hint:'Bacchus, orgia, and Cithaeron all point to ecstatic Bacchic worship.',feedback:'A Thȳias is a Bacchant. The elevated mythological comparison turns Dido’s movement through Carthage into ritual frenzy.'},
{type:'Poetic contraction',prompt:'What familiar verb form lies beneath spērāstī?',choices:['spērāvistī','spērāverās','spērābis'],answer:0,hint:'Perfect-tense -āvistī is often shortened in poetry and speech.',feedback:'Spērāvistī. Internal letters have been dropped: this is poetic contraction, not elision between two words.'},
{type:'Compressed symbol',prompt:'What ordinary idea does data dextera represent?',choices:['A pledge or promise of loyalty','A wound to the right hand','A command to begin sailing'],answer:0,hint:'The “given right hand” recalls a formal gesture between two people.',feedback:'A pledge or promise. Vergil compresses the relationship into the physical symbol of the joined right hand.'},
{type:'Recover the question',prompt:'What is Dido emphasizing with Mēne fugis?',choices:['“Is it me you are fleeing?”','“Are you fleeing with me?”','“Am I ordering you to flee?”'],answer:0,hint:'-ne marks the question; mē is the object of fugis.',feedback:'“Is it me you are fleeing?” Fronted mē and enclitic -ne concentrate the accusation on Dido herself.'},
{type:'Metaphorical command',prompt:'What does exue mentem ask Aeneas to do?',choices:['Put off or change his intention','Remove his armor','Explain his plan privately'],answer:0,hint:'Exuere literally means to take off clothing; here its object is mentem.',feedback:'Change his intention. Vergil treats a settled purpose like clothing that Aeneas could take off.'},
{type:'Elevated image',prompt:'What does quā sōlā sīdera adībam say about Dido’s former fāma?',choices:['Her reputation raised her to the stars','Her fame guided sailors at night','The gods promised her immortality'],answer:0,hint:'Sīdera adīre is spatial language applied to reputation.',feedback:'Her reputation raised her to the stars. The hyperbolic image makes the loss of honor feel like a fall from heaven.'},
{type:'Loaded vocabulary',prompt:'Why is hospes painful in cui mē moribundam dēseris hospes?',choices:['It reduces the man she treated as a husband to a mere guest','It declares Aeneas an enemy soldier','It identifies Iarbas as Dido’s host'],answer:0,hint:'Dido immediately contrasts hoc nōmen with conjuge.',feedback:'“Guest” replaces the hoped-for title “husband.” The ordinary relationship word exposes how little remains of their bond.'},
{type:'Compressed resemblance',prompt:'What does quī tē tamen ōre referret mean of the imagined child?',choices:['He would reproduce or resemble Aeneas in his face','He would report Aeneas’s words','He would bring Aeneas home'],answer:0,hint:'Ōre gives the feature in which the child would referre his father.',feedback:'The child would resemble Aeneas in his face. Vergil compresses “show his father’s likeness” into referret with an ablative.'}]},
{cite:'Aeneid 4.337–361',label:'Aeneas explains his duty',status:'Seen AP passage',title:'Aeneas answers with fate and duty',instruction:'Unpack ritual images, poetic place-names, alternate forms, elision, and metaphors for hearing and obligation.',lines:['“Prō rē pauca loquar. Neque ego hanc abscondere fūrtō','spērāvī (nē finge) fugam, nec conjugis umquam','praetendī taedās aut haec in foedera vēnī.','Mē sī fāta meīs paterentur dūcere vītam','auspiciīs et sponte meā compōnere cūrās,','urbem Trojānam prīmum dulcīsque meōrum','relliquiās colerem, Priamī tēcta alta manērent,','et recidīva manū posuissem Pergama victīs.','Sed nunc Ītaliam magnam Grȳnēus Apollō,','Ītaliam Lyciae jussēre capessere sortēs;','hic amor, haec patria est. Sī tē Karthāginis arcēs','Phoenissam Libycaeque aspectus dētinet urbis,','quae tandem Ausoniā Teucrōs cōnsīdere terrā','invidia est? Et nōs fās extera quaerere rēgna.','Mē patris Anchīsae, quotiēns ūmentibus umbrīs','nox operit terrās, quotiēns astra ignea surgunt,','admonet in somnīs et turbida terret imāgō;','mē puer Ascanius capitisque injūria cārī,','quem rēgnō Hesperiae fraudō et fātālibus arvīs.','Nunc etiam interpres dīvum Jove missus ab ipsō','(testor utrumque caput) celerīs mandāta per aurās','dētulit: ipse deum manifēstō in lūmine vīdī','intrantem mūrōs vōcemque hīs auribus hausī.','Dēsine mēque tuīs incendere tēque querēlīs;','Ītaliam nōn sponte sequor.”'],questions:[
{type:'Recover ordinary language',prompt:'What does fūrtō contribute to abscondere … fugam?',choices:['Secretly or by stealth','After committing a theft','By an act of war'],answer:0,hint:'The ablative describes the manner in which the departure would be concealed.',feedback:'Secretly or by stealth. A concrete noun is used adverbially to compress the manner of the action.'},
{type:'Ritual metaphor',prompt:'What ordinary claim is contained in conjugis praetendī taedās?',choices:['I never presented the wedding torches or claimed marriage','I never burned Dido’s palace','I never concealed a signal fire'],answer:0,hint:'Wedding torches belonged to Roman marriage ritual.',feedback:'Aeneas says he never offered marriage. The ritual object “torches” stands for the entire marital commitment.'},
{type:'Elision',prompt:'Which version shows the elision in Neque ego?',choices:['Nequ(e) ego','Neque (e)go','No elision occurs'],answer:0,hint:'A final vowel is suppressed before the next word begins with a vowel.',feedback:'Nequ(e) ego. Final -e is elided before ego. This happens within the verse; the written spelling remains complete.'},
{type:'Alternate poetic form',prompt:'What familiar spelling lies beneath relliquiās?',choices:['reliquiās','relinquiās','reliquērās'],answer:0,hint:'Vergil sometimes uses an expanded or doubled consonant spelling for metrical purposes.',feedback:'Reliquiās. Relliquiās is a poetic alternate form, not a different vocabulary word.'},
{type:'Poetic place-name',prompt:'What ordinary place does Pergama represent?',choices:['Troy','Carthage','Italy'],answer:0,hint:'Priamī tēcta and urbem Trojānam establish the location.',feedback:'Troy. Pergama, originally the citadel, serves as an elevated poetic name for the Trojan city.'},
{type:'Poetic names and epithets',prompt:'Whom do Grȳnēus Apollō and Lyciae sortēs represent as the source of the command?',choices:['Apollo and his oracle','Jupiter and Mercury','Anchises and Ascanius'],answer:0,hint:'Grynean and Lycian are cult and geographic associations of Apollo.',feedback:'Apollo and his oracle. Elevated titles and place associations replace a plain statement that Apollo ordered him to seek Italy.'},
{type:'Recover familiar places',prompt:'Which ordinary equivalents match Ausonia, Teucrī, and Hesperia?',choices:['Italy, Trojans, Italy/the western land','Carthage, Greeks, Troy','Sicily, Romans, Africa'],answer:0,hint:'All three belong to the contrast between Dido’s Carthage and Aeneas’s destination and people.',feedback:'Italy, Trojans, and Italy/the western land. Epic geography makes familiar peoples and destinations look unfamiliar.'},
{type:'Compressed moral vocabulary',prompt:'Why does Aeneas say fās rather than simply licet?',choices:['He presents seeking a foreign kingdom as divinely permitted','He says the journey is easy','He admits the voyage is illegal'],answer:0,hint:'Fās concerns what divine law allows.',feedback:'Fās frames the journey as religiously and morally permitted, not merely possible or convenient.'},
{type:'Poetic epithet',prompt:'Who is interpres dīvum Jove missus ab ipsō?',choices:['Mercury','Apollo','Anchises'],answer:0,hint:'This god carries Jupiter’s commands through the air.',feedback:'Mercury. “Interpreter of the gods” replaces his name with the role that matters in the scene.'},
{type:'Sensory metaphor',prompt:'What ordinary action lies beneath vōcem hīs auribus hausī?',choices:['I heard the voice with my own ears','I repeated the message aloud','I drank from a sacred spring'],answer:0,hint:'Haurīre literally means “draw” or “drink in,” but the object is vōcem.',feedback:'Aeneas says he heard the voice himself. Vergil turns hearing into drinking or drawing the sound into the ears.'},
{type:'Read for meaning',prompt:'What does Ītaliam nōn sponte sequor claim?',choices:['He pursues Italy unwillingly, under obligation','He has freely chosen Italy over Dido','He no longer intends to sail'],answer:0,hint:'Nōn sponte means “not of my own will.”',feedback:'Aeneas claims that duty, not personal desire, drives him toward Italy.'}]}
];
VERGIL_PASSAGES.sort((a,b)=>Number(a.cite.match(/4\.(\d+)/)[1])-Number(b.cite.match(/4\.(\d+)/)[1]));
